---
- name: load variables
  include_vars: all.yml

- name: install apt sources configuration
  template:
    src: etc_apt_sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  notify: apt update cache

- name: install apt sources configuration
  template:
    src: etc_apt_sources.list.d_10backports.list.j2
    dest: /etc/apt/sources.list.d/10backports.list
    owner: root
    group: root
    mode: 0644
  notify: apt update cache
  when: apt_with_backports

- meta: flush_handlers

- name: install programs
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
   cache_valid_time: 1800
  with_items:
    - aptitude
    - debian-goodies

- name: install aptitude configuration
  copy:
    src: etc_apt_apt.conf.d_99aptitude
    dest: /etc/apt/apt.conf.d/99aptitude
    owner: root
    group: root
    mode: 0644

- name: install extra tools
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 1800
  with_items:
    - apt-file
    - apt-listchanges
  notify:
    - update apt_file_cache
  when: apt_install_extra
